### ISSUE TITLE
Angular源码解析参考文章

### ISSUE THREAD

**Issue by Wscats** [Wscats/articles#15]
angular源码一，module加载器
http://blog.csdn.net/dagouaofei/article/details/38085357

angularjs源码分析之：angularjs执行流程
https://segmentfault.com/a/1190000002549996

用angularjs遇到的坑们
http://www.cnblogs.com/zhrj000/p/3383898.html

Angular源码理解–启动过程
http://blog.csdn.net/ybdesire/article/details/50719173

angularjs1.3.0源码解析之执行流程
http://www.html-js.com/article/Source-code-analysis-original-the-execution-flow-of-angularjs130-source-code-analysis

AngularJS模块详解
http://blog.csdn.net/woxueliuyun/article/details/50962645
在路由里面实现延迟加载，注意$.getScript要先加载jQuery才能运行

```
resolve: {
                        delay: function($q) {
                            var delay = $q.defer(),
                                load = function() {
                                    $.getScript('.js', function() {
                                        delay.resolve();
                                    });
                                };
                            load();
                            return delay.promise;
                        }
                    }
```

angular.fromJson方法与toJson方法
http://blog.csdn.net/itsonglin/article/details/47429867

angularjs源码分析之：angularjs执行流程
http://www.cnblogs.com/Leo_wl/p/3771304.html

Angular showcase!
http://showcase.ngnice.com/#/home/home

**Comment by ybdesire** [comment]
Thanks for referring my blog 《Angular源码理解–启动过程》
