### ISSUE TITLE
Mac小技巧

### ISSUE THREAD

**Issue by Wscats** [Wscats/articles#46]
# 系统所有隐藏文件显示

系统所有隐藏文件显示，终端下输入以下命令
```bash
defaults write com.apple.finder AppleShowAllFiles -bool true
```
或者用快捷键
```bash
command + shift + .
```
# 显示文件夹所有的隐藏文件

```bash
ls -a
```

# 将文件夹拉到终端获取文件或者文件夹路径

# 查找终端

在finder里面搜索“终端”

# 查找文件

在finder中按以下三个组合按键，可以查找文件，例如host文件
```bash
command + shift + g
```

# IOS模拟器的Home快捷键

```bash
command + shift + h
```

# 输入法切换

```bash
command + 空格
```
不过现在这个快捷键好像改了，影响不大，不过我是被搜过输入法惯着了，改不回来

# 管理员权限

输入一下命令会获取管理员权限，在某些情况下要用到管理员权限，输入正确密码才能获取该权限
```bash
sudo -i
```
例如：在mac系统下安装node模块包，要在npm开头加上sudo，用管理员权限安装，不然没有权限去新建文件夹等导致安装失败

# Macbook设置热点

[Mac做wifi热点](http://jingyan.baidu.com/article/a65957f489d4af24e67f9b29.html)

# 打开根目录文件

用终端输入以下命令
```bash
open .    #打开使用者的目录
open /    #打开系统根目录
```

# 安装brew

参考[Homebrew](https://brew.sh/index_zh-cn.html)

在终端输入以下命令，安装brew之后，可以利用它来安装其他常用的包
```bash
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

# 屏幕截图

```bash
command + shift + 4
```

# 远程连接

试了几个发现**Parallels Client**比较好用，直接在App Store下载即可

# Mamp Pro

[Mac 中 mamp pro 的 localhost 显示为 403 Forbidden](https://www.jianshu.com/p/551f12654e4a)

# Xclient

推荐一个Mac破解软件的网站，上面有大量的工具，新手值得尝试，不过最好还是支持正版，谢谢🙏

[精品MAC应用分享](http://xclient.info)

# 谷歌访问助手

I find a good extension which name is the assistant of accessing Google in order to visit some technology sites. You can search the key word on the Internet in any browsers. After you download it, you can install it in chrome. Through it, many services of Google will be normally used. It's extremely wonderful and useful extension I recommend.

# win to go

可以参考这篇文章

[说走就走的「Windows」—— Windows To Go 制作详解](https://sspai.com/post/44699)

有几点要注意的是我在PD虚拟机里面制作的启动盘，移动硬盘要选择用虚拟机读取，而不是mac系统本身，不然win to go无法获取移动硬盘

还有注意win启动盘弄好了之后，要用`command+r`进入设置几个关键设置，允许读取外盘系统和禁止网络（不然启动的时候会一直要求网络），记得要准备一个U盘再mac系统中下载win驱动(启动转换助理BootCamp)，然后烤进去在win系统中安装，因为win启动之后所有驱动都没有的

# Postman

5 million developers use [Postman](https://www.getpostman.com/apps). You should too!

# Wine

先安装[Xquartz](https://www.xquartz.org/)，然后再安装[Wine](https://dl.winehq.org/wine-builds/macosx/download.html)

配置`Wine`的环境路径
```bash
test "$?BASH_VERSION" = "0" || eval 'setenv() { export "$1=$2"; }';setenv PATH "/Applications/Wine Stable.app/Contents/Resources/start/bin:/Applications/Wine Stable.app/Contents/Resources/wine/bin:$PATH";
```
使用的时候
```bash
wine xxx.exe
```

# 清理全部 node_modules 文件夹

[你的硬盘已满，清理 node_modules 来腾出空间](https://www.jianshu.com/p/de2dcb862465)

# gitkraken

一个很好用的 git 管理工具

https://www.gitkraken.com/

破解版教程： https://github.com/5cr1pt/GitCracken/tree/master/GitCracken

<img width="457" alt="截屏2020-03-26下午3 42 03" src="https://user-images.githubusercontent.com/17243165/77621980-6d602e80-6f78-11ea-878e-b2edbabbe702.png">

**Comment by meow4world** [comment]
仲有無更多小技巧？例如xampp集成环境配置php~:kissing_smiling_eyes:
