### ISSUE TITLE
Git和SVN区别&&AMD和CMD的区别

### ISSUE THREAD

**Issue by Wscats** [Wscats/articles#47]
[参考文章](http://blog.jobbole.com/31444/)
1.GIT是分布式的，SVN不是
2.GIT把内容按元数据方式存储，而SVN是按文件
3.GIT分支和SVN的分支不同
4.GIT没有一个全局的版本号，而SVN有
5.GIT的内容完整性要优于SVN

Git一般是命令行来完成的
[git指令](http://rj.baidu.com/soft/detail/30195.html?ald)
SVN一般用图形化界面，因为它的图形化界面比较友好
用SVN是要下载[TortoiseSVN](http://rj.baidu.com/soft/detail/11993.html?ald)

SVN安装完后要重启才能使用

SVN有一个绿色的钩

Git拉项目的是
`git clone ssh地址`

SVN拉项目是
`客户端SVN checkout`

**Comment by Wscats** [comment]
AMD跟CMD的区别
[AMD 和 CMD 的区别有哪些？](http://www.zhihu.com/question/20351507/answer/14859415)
[与 RequireJS 的异同](https://github.com/seajs/seajs/issues/277)

相同之处：RequireJS 和 Sea.js 都是模块加载器，倡导模块化开发理念

不同之处：执行模块的机制大不一样，SeaJS对模块的态度是懒执行, 而RequireJS对模块的态度是预执行，CMD是SeaJS按需加载

**Comment by GuojunYin** [comment]
very good

**Comment by qq452261789** [comment]
完美

**Comment by jhao520** [comment]
围观

**Comment by fiaxiong** [comment]
熊丽平：https://fiaxiong.github.io/more/

**Comment by LikimQ** [comment]
https://github.com/Wscats/Good-text-Share/issues/47我第一个！

**Comment by LikimQ** [comment]
https://github.com/Wscats/Good-text-Share/issues/47  我第一个

**Comment by LikimQ** [comment]
https://github.com/LikimQ/likim 我第一个

**Comment by kiven666** [comment]
威武
