### ISSUE TITLE
Matrix理解与前端运用

### ISSUE THREAD

**Issue by onelady** [Wscats/articles#83]
## 前言
以前在写AS3的时候一直对Matrix有着比较模糊的概念，碍于之后前段开发没有类似的接触，就一直置之不理。有幸，前段时间由于技术项目需要，项目中使用到createJs框架对图形进行操作和计算，再次接触到Matrix计算，能有时间对它进行进一步的学习和了解。最后决定写一篇文章，汇总介绍一下Matrix的基本使用。
可能大部分前端开发者和我一样，在现在前端日常开发中，使用到Matrix的场景并不多。但是在需要使用到图形变换时，例如css3变换、SVG、canvas等时，Matrix的计算又离我们如此之近。
## 什么是Matrix
Matrix就是矩阵，对于矩阵的概念在数学中其实就有所涉及，这里不多做累述。下面主要讲的是Matrix对图形的描述。
对于图形的描述离不开坐标系，而在平面坐标系中，平面上的元素，就是点，线，面，而线就是由一个个点组成的，而是由一条条线组成的，所以归根结底，平面上所有的图形都是由点组成的。
而在我们坐标系中，一个点就是由一对x，y值组成的，p = {x, y}。而在平面上，过两点间的，我们可以画一条直线，所以我们一般通过 p1, p2可定义一条直线，e = {p1, p2}，而图形呢，则是由众多的点和点之间的的线段组成的。所以，其实平面上的图形变换，就是点坐标位置的变换。而Matrix就是对图形产生形变结果集合的描述产物。
在我们现在接触到的图形变化中，Matrix分为两种，Matrix2D和Matrix3D。Marix2D是3\*3的矩阵序列，Matrix3D是4\*4的矩阵序列。接下来我们主要介绍平面图形变化使用的Marix2D。
## Matrix2D
如上文所说，martrix2D是一个3\*3的矩阵，3\*3每一个数字都有特殊含义，我们涉及到的形变描述只会改变第一行和第二行的数字。在平面坐标系中，每个图形都会对应一个Matrix，当新建一个图形时，Matrix的值如下：
 
```
//以createJs为例
let matrix = new createjs.Matrix2D(); 
/* 
*  matrix => | a c e |   =>   | 1 0 0 |
*            | b d f |        | 0 1 0 |
*            | 0 0 1 |        | 0 0 1 |
*/
```
 
如上图可见，在Matrix新建时，并不是所有的值都是0的，而且每一个数分别代表不一样的意义。但是在2D平面中所有形变都不会涉及到第三行数字，所以一般描述matrix2D时，都只会有两行数字，6个字母表示。在Matrix中：

* a：表示水平缩放
* b：表示水平拉伸
* c：表示垂直拉伸
* d：表示垂直缩放
* e：表示水平位移
* f：表示垂直位移

### 什么是Origin
既然Matrix是对平面图形进行描述，那么平面坐标系中还有一个不能少的属性那就是`origin`（原点），所有的形变，例如旋转（rotate）、形变（skew）等，都是以原点为中心来进行的，在css3中叫做`transform-origin`。从一个例子说明一下：
 
```
/* 
*   | x1 |   | a c e | | x |   | ax + cy + e |
*   | y1 | = | b d f | | y | = | bx + dy + f |
*   | 1  |   | 0 0 1 | | 1 |   |      1      |
*/
```
 
其中的x y是元素变换之前的中心点，即transform-origin的值，x1 y1是元素变换之后的transform-origin值。
假设一个元素的中心点为100,100，将该元素向右平移200px，向下平移100px后，中心点坐标为:
x1 = ax + cy + e = 1\*100 + 0\*100 + 200 = 300
y2 = 0\*100 + 1\*100 + 100 = 200
平移后的中心点坐标为300，200
### Canvas的Origin 和 CSS3的transform-origin 的差别
CSS3中的`transform-origin`默认是元素的中点，css3的旋转和形变都是自动以图形的中点进行，除非手动改变`transform-origin`的值。但是在canvas或者一些图形框架（raphael、createjs等）中，Matrix的原点都会默认设置在左上角。
## Matrix中的Transform
在matrix中，transform()方法代表了matrix的所有形变内容。而transform()方法下面又被分解为多个分量方法：
* Translation(tx, ty) 平移
* Scale(sx, sy) 缩放
* Rotate(deg) 旋转
* Skew(dx, dy) 拉伸，比较特殊
### 平移 Translation
平移：translate(tx, ty) 等同于 matrix(1, 0, 0, 1, tx, ty);
Translation()函数有两个参数传入，影响的是x的偏移量和y的偏移量。其只会影响Matrix中e, f两个变量，可以说在只发生平移的情况下，translate(tx, ty) 等同于 matrix(1, 0, 0, 1, tx, ty)，前四个参数不会影响，只会叠加tx，ty。
例如：
 
```
/* 
*   | a c e |    translate(tx,ty)   | a c e+tx |
*   | b d f |   =================>  | b d f+ty |
*   | 0 0 1 |                       | 0 0 1    |
*/
```
 
---
 
### 缩放 Scale
缩放：scale(sx, sy) 等同于 matrix(sx, 0, 0, sy, 0, 0);
scale()函数有两个参数传入，水平缩放比和垂直缩放比。其会对Matrix中a和d两个变量乘以比例，其他变量保持不变。
例如：
 
```
 
/* 
*   | a c e |    scale(sx,sy)    | a*sx  c     e |
*   | b d f |   ==============>  | b     d*sy  f |
*   | 0 0 1 |                    | 0     0     1 |
*/
```
 
---
 
### 旋转 Rotate
旋转：rotate(deg) 等同于 matrix(cos(deg), sin(deg), -sin(deg), cos(deg), 0, 0);
rotate()函数有一个参数传入，旋转的度数。在计算时，会影响a、b、c、d四个值，其他变量保持不变。
例如：
 
```
/* 
*   | a c e |    rotate(deg)   | a*cos(deg) c*-sin(deg) e |
*   | b d f |   ============>  | b*sin(deg) d*cos(deg)  f |
*   | 0 0 1 |                  | 0          0           1 |
*/
```
 
---
 
### 拉伸 Skew
拉伸：skew(degx, degy) 等同于 matrix(1, tan(degy), tan(degx), 1, 0, 0);
skew()函数有两个参数传入，是水平角度分量，和垂直角度分量。会影响b、c两个参数，其他保持不变。
但是这个方法比较特殊，因为它可以被`Scale()`和`rotation()`表示。所以在不同的框架中，对这个函数的具体表现和实现也会有所差异，例如在createjs中`Skew()`函数会改变图形的高度，而在css3以及raphael框架中则不会。
 
---
 
### 形变 Transform
形变：Transform(x, y, scaleX, scaleY, rotation, skewX, skewY, regX, regY)
可以看出Transform()方法是一个汇总方法，其作用不做累述。
 
---
 
## 3D变换中的矩阵
在3D变换中，Matrix3D较2D从3\*3变为4\*4。从二维到三维，涉及到的变量是从4个到9个。其实，本质上很多东西都与2D一致的，只是复杂度不一样而已。这里就举一个简单的3D缩放变换的例子：
scale(sx,sy,sz),就应该等同于matrix3d(sx, 0, 0, 0, 0, sy, 0, 0, 0, 0, sz, 0, 0, 0, 0, 1)，而涉及到的矩阵就应该是：
 
```
/* 
*  | sx 0  0  0 |
*  | 0  sy 0  0 |
*  | 0  0  sz 0 |
*  | 0  0  0  1 |
*/
```
 
## 总结
以上就是关于Matrix的变换内容，在平时的开发中越来越多的场景会运用到Matrix的计算。这里仅仅是介绍了Matrix2D下形变的各个方法和计算方式，没有放demo。而且实际计算中有可能会遇到更为复杂的情况，可以在实践中去尝试一下分量计算和获取Matrix各个变量进行比较。

**Comment by SiZapPaaiGwat** [comment]
👍
